# Generated by Django 4.2.7 on 2025-08-08 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ISBN')),
                ('title', models.TextField(verbose_name='Başlık')),
                ('authors', models.TextField(verbose_name='Yazarlar')),
                ('publish_date', models.CharField(blank=True, max_length=50, verbose_name='Yayın Tarihi')),
                ('number_of_pages', models.IntegerField(blank=True, null=True, verbose_name='Sayfa Sayısı')),
                ('publishers', models.TextField(blank=True, verbose_name='Yayınevleri')),
                ('languages', models.CharField(blank=True, max_length=100, verbose_name='Diller')),
                ('quantity', models.IntegerField(default=1, verbose_name='Adet')),
                ('available_quantity', models.IntegerField(default=1, verbose_name='Mevcut Adet')),
                ('shelf', models.CharField(blank=True, max_length=50, verbose_name='Raf')),
                ('cupboard', models.CharField(blank=True, max_length=50, verbose_name='Dolap')),
                ('image_path', models.CharField(blank=True, max_length=200, verbose_name='Resim Yolu')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Kapak Resmi')),
                ('last_borrowed_date', models.DateTimeField(blank=True, null=True, verbose_name='Son Ödünç Alınma Tarihi')),
                ('total_borrow_count', models.IntegerField(default=0, verbose_name='Toplam Ödünç Alınma Sayısı')),
                ('qr_code', models.CharField(blank=True, max_length=200, verbose_name='QR Kod Yolu')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Barkod')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='Basım')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Ortalama Puan')),
                ('review_count', models.IntegerField(default=0, verbose_name='Değerlendirme Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Kitap',
                'verbose_name_plural': 'Kitaplar',
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=200, verbose_name='Arama Terimi')),
                ('result_count', models.IntegerField(verbose_name='Sonuç Sayısı')),
                ('search_date', models.DateTimeField(auto_now_add=True, verbose_name='Arama Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Arama Geçmişi',
                'verbose_name_plural': 'Arama Geçmişleri',
                'db_table': 'search_history',
                'ordering': ['-search_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Rezervasyon Tarihi')),
                ('expiry_date', models.DateTimeField(verbose_name='Son Geçerlilik Tarihi')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('fulfilled', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu')], default='active', max_length=20, verbose_name='Durum')),
                ('queue_position', models.IntegerField(blank=True, null=True, verbose_name='Sıra Numarası')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Bildirim Gönderildi')),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book', verbose_name='Kitap')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accounts.member', verbose_name='Üye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Rezervasyon',
                'verbose_name_plural': 'Rezervasyonlar',
                'db_table': 'reservations',
                'ordering': ['queue_position', 'reservation_date'],
            },
        ),
        migrations.CreateModel(
            name='OnlineBorrowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_date', models.DateField(verbose_name='Teslim Alma Tarihi')),
                ('pickup_time', models.TimeField(verbose_name='Teslim Alma Saati')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Red Nedeni')),
                ('approved_by', models.CharField(blank=True, max_length=80, verbose_name='Onaylayan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Onaylanma Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_requests', to='books.book', verbose_name='Kitap')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_requests', to='accounts.member', verbose_name='Üye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Online Ödünç Talebi',
                'verbose_name_plural': 'Online Ödünç Talepleri',
                'db_table': 'online_borrow_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Kitap')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kitap Kategorisi',
                'verbose_name_plural': 'Kitap Kategorileri',
                'db_table': 'book_categories',
                'unique_together': {('book', 'category')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(blank=True, through='books.BookCategory', to='books.category', verbose_name='Kategoriler'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Çok Kötü'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Mükemmel')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puan')),
                ('comment', models.TextField(blank=True, verbose_name='Yorum')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Faydalı Bulunma Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book', verbose_name='Kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Değerlendirme',
                'verbose_name_plural': 'Değerlendirmeler',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
    ]
