# Generated by Django 4.2.7 on 2025-08-08 16:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='Ödünç Alma Tarihi')),
                ('due_date', models.DateTimeField(verbose_name='İade Tarihi')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Gerçek İade Tarihi')),
                ('renew_count', models.IntegerField(default=0, verbose_name='Yenileme Sayısı')),
                ('condition_on_borrow', models.CharField(choices=[('good', 'İyi'), ('fair', 'Orta'), ('poor', 'Kötü')], default='good', max_length=50, verbose_name='Ödünç Alırkenki Durum')),
                ('condition_on_return', models.CharField(blank=True, choices=[('good', 'İyi'), ('fair', 'Orta'), ('poor', 'Kötü')], max_length=50, verbose_name='İade Ederkenki Durum')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('returned', 'İade Edildi'), ('overdue', 'Gecikmiş'), ('lost', 'Kayıp'), ('damaged', 'Hasarlı')], default='active', max_length=20, verbose_name='Durum')),
                ('fine_amount', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ceza Tutarı')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.book', verbose_name='Kitap')),
                ('librarian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan Kütüphaneci')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.member', verbose_name='Üye')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('borrow', 'Ödünç Verildi'), ('return', 'İade Edildi'), ('renew', 'Yenilendi'), ('overdue', 'Gecikti'), ('fine_applied', 'Ceza Uygulandı'), ('fine_paid', 'Ceza Ödendi'), ('fine_waived', 'Ceza Affedildi')], max_length=50, verbose_name='İşlem')),
                ('details', models.TextField(blank=True, verbose_name='Detaylar')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yapan')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='transactions.transaction', verbose_name='İşlem')),
            ],
            options={
                'verbose_name': 'İşlem Geçmişi',
                'verbose_name_plural': 'İşlem Geçmişleri',
                'db_table': 'transaction_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tutar')),
                ('reason', models.CharField(choices=[('late_return', 'Geç İade'), ('damaged', 'Hasarlı İade'), ('lost', 'Kayıp Kitap'), ('other', 'Diğer')], default='late_return', max_length=100, verbose_name='Sebep')),
                ('status', models.CharField(choices=[('unpaid', 'Ödenmedi'), ('paid', 'Ödendi'), ('waived', 'Affedildi')], default='unpaid', max_length=20, verbose_name='Durum')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Ödenme Tarihi')),
                ('waived_date', models.DateTimeField(blank=True, null=True, verbose_name='Affedilme Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='accounts.member', verbose_name='Üye')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_fines', to=settings.AUTH_USER_MODEL, verbose_name='Tahsil Eden')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='transactions.transaction', verbose_name='İşlem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ceza',
                'verbose_name_plural': 'Cezalar',
                'db_table': 'fines',
                'ordering': ['-created_date'],
            },
        ),
    ]
