# Generated by Django 4.2.7 on 2025-08-08 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Şablon Adı')),
                ('subject', models.CharField(max_length=200, verbose_name='Konu')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Kullanılabilir değişkenler listesi (JSON)', verbose_name='Değişkenler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'E-posta Şablonu',
                'verbose_name_plural': 'E-posta Şablonları',
                'db_table': 'email_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('due_reminder', 'İade Hatırlatması'), ('overdue', 'Gecikme Bildirimi'), ('reservation_ready', 'Rezervasyon Hazır'), ('reservation_expired', 'Rezervasyon Süresi Doldu'), ('fine_applied', 'Ceza Uygulandı'), ('book_returned', 'Kitap İade Edildi'), ('renewal_reminder', 'Yenileme Hatırlatması'), ('system_message', 'Sistem Mesajı'), ('welcome', 'Hoş Geldin Mesajı'), ('book_request_approved', 'Kitap Talebi Onaylandı'), ('book_request_rejected', 'Kitap Talebi Reddedildi'), ('other', 'Diğer')], default='other', max_length=50, verbose_name='Tip')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Gönderildi')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-posta Gönderildi')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS Gönderildi')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('read_date', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Tarihi')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Geçerlilik Süresi')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.member', verbose_name='Üye')),
                ('related_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book', verbose_name='İlgili Kitap')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.transaction', verbose_name='İlgili İşlem')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'db_table': 'notifications',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('data_type', models.CharField(choices=[('string', 'Metin'), ('integer', 'Sayı'), ('float', 'Ondalık'), ('boolean', 'Mantıksal'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Veri Tipi')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Düzenlenebilir')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Güncelleyen')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_due_reminder', models.BooleanField(default=True, verbose_name='E-posta İade Hatırlatması')),
                ('email_overdue', models.BooleanField(default=True, verbose_name='E-posta Gecikme Bildirimi')),
                ('email_reservation_ready', models.BooleanField(default=True, verbose_name='E-posta Rezervasyon Hazır')),
                ('email_fine_applied', models.BooleanField(default=True, verbose_name='E-posta Ceza Bildirimi')),
                ('sms_due_reminder', models.BooleanField(default=False, verbose_name='SMS İade Hatırlatması')),
                ('sms_overdue', models.BooleanField(default=False, verbose_name='SMS Gecikme Bildirimi')),
                ('sms_reservation_ready', models.BooleanField(default=False, verbose_name='SMS Rezervasyon Hazır')),
                ('web_notifications', models.BooleanField(default=True, verbose_name='Web Bildirimleri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Bildirim Tercihi',
                'verbose_name_plural': 'Bildirim Tercihleri',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-posta'), ('sms', 'SMS'), ('web', 'Web'), ('push', 'Push')], max_length=20, verbose_name='Kanal')),
                ('recipient', models.CharField(max_length=200, verbose_name='Alıcı')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız'), ('bounced', 'Geri Döndü')], default='pending', max_length=20, verbose_name='Durum')),
                ('error_message', models.TextField(blank=True, verbose_name='Hata Mesajı')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Zamanı')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Edilme Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_history', to='notifications.notification', verbose_name='Bildirim')),
            ],
            options={
                'verbose_name': 'Bildirim Geçmişi',
                'verbose_name_plural': 'Bildirim Geçmişleri',
                'db_table': 'notification_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
